### ISSUE TITLE
slide update วันที่13/12/23

### ISSUE THREAD

**Issue by PhobThePang** [PhobThePang/MPCforus#10]
Weekly Slide Update

Create a new slide and link here.
Slide continuity of content.
Short and Compact content.
Make it understandable.
**Treat slides like notes

**Comment by ICON08** [comment]
https://docs.google.com/presentation/d/1ISeZgNxWgXynkt8A31TkREACSGm0XE0E0WIOCLF87As/edit?usp=sharing
