### ISSUE TITLE
Slide Updates 03/01/24

### ISSUE THREAD

**Issue by namoxd101** [PhobThePang/MPCforus#24]
Weekly Slide Update

Create a new slide and link here.
Slide continuity of content.
Short and Compact content.
Make it understandable.
**Treat slides like notes

**Comment by ICON08** [comment]
https://docs.google.com/presentation/d/1JznppT1_7nvyJ1tv3YtIf_v--qVfLofHWzWHxfQ3kpI/edit?usp=sharing
