### ISSUE TITLE
BE Diagram Update

### ISSUE THREAD

**Issue by namoxd101** [PhobThePang/MPCforus#25]
Fix and Update back-end's diagram till it is passed.

- [x] Drafting
- [x] Make the diagram
link: [miro](https://miro.com/welcomeonboard/WnUwekZnYllWS2pLR2hVNDBaZEpsV2dNMW9CYmRXYWxJZjNaekVsallhOGRrWnhMTUd5Y3dkd2MxQmtBWnBTdnwzNDU4NzY0NTMxODMyNjExMDAxfDI=?share_link_id=145150528661)

**Comment by PhobThePang** [comment]
https://lucid.app/lucidchart/a412b380-0dbd-4ea2-b55a-4ba0b87986bc/edit?invitationId=inv_81d1da9d-d0b9-451a-a976-401ef7b376de&page=0_0#


.

**Comment by PhobThePang** [comment]
https://lucid.app/join

RAB NNJ
