### ISSUE TITLE
Kiosk Update 2

### ISSUE THREAD

**Issue by namoxd101** [PhobThePang/MPCforus#28]
User Experience ของ Kiosk: ลูกค้าต้องเจออะไรขณะใช้งาน

Diagram Kiosk: การทำงานของ kiosk diagram คล้ายๆ ของ Back-End

Cloud Server ต้องเก็บข้อมูลอะไรบ้าง

**Comment by ICON08** [comment]
add me bro

**Comment by ICON08** [comment]
test

**Comment by ICON08** [comment]
https://www.canva.com/design/DAF4y2nmUC8/2E29drrfC6fGoo2QDdMf7g/edit?utm_content=DAF4y2nmUC8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
