### ISSUE TITLE
Payment Process 2

### ISSUE THREAD

**Issue by namoxd101** [PhobThePang/MPCforus#29]
Credit/Debit Cards: เอาให้ทำงานได้ก่อน ไม่เอาแบบซับซ้อน ระบบดำเนินการชำระผ่านเครดิตการ์ดใช้งานยังไง? (เช่น การ์ดส่งคำขออนุมัติ มีoperator ยอมรับ แล้วหักเงิน ในอินเตอร์เน็ต)

Customer Account: ไม่อยากให้ลูกค้านั่งจิ้มข้อมูลเยอะ เป็นไปได้อยากให้ระบบจำบัตรเครดิตลูกค้านี้ได้ เก็บเป็นสะสมแต้ม แล้วจำข้อมูลรถไฟฟ้าไปเลย

POS/Tablet-Kiosk: ระบบเครื่องจ่ายตังค์ต่างๆ (ดูใน update ล่าสุด)

**Comment by Khempitcha** [comment]
![Image](https://github.com/PhobThePang/MPCforus/assets/152351753/a44b14f8-c9c2-461d-8790-0b48e06492ae)
