### ISSUE TITLE
Slide Update 09/01/24

### ISSUE THREAD

**Issue by namoxd101** [PhobThePang/MPCforus#30]
Weekly Slide Update

Create a new slide and link here.
Slide continuity of content.
Short and Compact content.
Make it understandable.
**Treat slides like notes

**Comment by ICON08** [comment]
https://docs.google.com/presentation/d/10XxoH-1MniWq1emCgC7PlU7yMPiCwjgFnxSZudrmUfY/edit?usp=sharing
