### ISSUE TITLE
Slide Update 17/01/24

### ISSUE THREAD

**Issue by namoxd101** [PhobThePang/MPCforus#31]
Weekly Slide Update

Create a new slide and link here.
Slide continuity of content.
Short and Compact content.
Make it understandable.
**Treat slides like notes

**Comment by PhobThePang** [comment]
https://docs.google.com/presentation/d/1zX0qFZ-ouL3JNxwl1EK1-4I3oz7DW6El-V9JbXFE0Fk/edit?usp=sharing
