### ISSUE TITLE
A1 content

### ISSUE THREAD

**Issue by namoxd101** [PhobThePang/MPCforus#38]
Product Components (What do they do?)

1. Multiport Charger side
     1.1. What can it do?
     1.2. What are the equipment?
2. Kiosk side
     2.1. What can it do?

Product systems (How do they work?)

1. Multiport Charger side
2. Kiosk side
3. Diagram of MPC with Kiosk (all in one)

Then send to @ICON08

**Comment by PhobThePang** [comment]
[List backend](https://docs.google.com/spreadsheets/d/1_jGbc_andSoi8BE8Eh3N_TPb4XXff3erGOuG-zBcVyo/edit#gid=0)
