### ISSUE TITLE
Flowchart of MPC unit

### ISSUE THREAD

**Issue by PhobThePang** [PhobThePang/MPCforus#4]
Create Flowchart/Workflow diagrams.
For better understanding of each system units including:
1. User Experience and Interaction
2. Back-End logic

- [x] information
- [x] plotลงflowchart
link : https://lucid.app/lucidchart/65c1bf3a-569f-4224-a772-4faf7df7cb5b/edit?viewport_loc=-1867%2C-773%2C2167%2C1111%2C0_0&invitationId=inv_0899890e-b68c-48bd-8bef-3d7964194782

**Comment by PhobThePang** [comment]
FYI

![Image](https://github.com/PhobThePang/MPCforus/assets/150700521/8c9d6cee-50d4-46fc-b4ff-e63c3b171a80)

**Comment by ICON08** [comment]
![Image](https://github.com/PhobThePang/MPCforus/assets/150206723/a268ddea-6762-4937-bd26-a70e2db5fd17)
