### ISSUE TITLE
Payment Process

### ISSUE THREAD

**Issue by namoxd101** [PhobThePang/MPCforus#6]
Research and Compare (Pros and Cons) about payment methods.

**Comment by PhobThePang** [comment]
- [x] หาข้อมูลอย่างน้อย3-5Process
- [x] นำข้อมูลลงมาใส่ในexcel

**Comment by PhobThePang** [comment]
![Image](https://github.com/PhobThePang/MPCforus/assets/150700521/b563ef7f-deaa-47fc-9080-3786085fc57c)

**Comment by PhobThePang** [comment]
https://docs.google.com/spreadsheets/d/1x5ZVR-pYXvI8_xjUAflAxesd0yCkGtdhVZjn4lNUAu8/edit?usp=sharing

**Comment by PhobThePang** [comment]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>
payment method | ความสะดวกในการใช้ | popularity | กลุ่มเป้าหมาย(user) | pros |   |   |   |   |   | c0ons |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
credit card | universal |   |   | Widely Accepted,Convenience(no need for apps),Security |   |   |   |   |   | Transaction Fees, need good infrastructure |   |   |   |  
PromptPay QR Code. | thailand most used |   | Residents and locals | quick,wide in thailand, direct with bank |   |   |   |   |   | dependency on mobile phones |   |   |   |  
true money wallet |   |   |   | widely use in thailand |   |   |   |   |   | Not Universal |   |   |   |  
Rabbit-Line play | paired with LINE app |   | Line app users | Part of the LINE messaging app |   |   |   |   |   | dependency on line app |   |   |   |  
online banking |   |   |   | direct with bank |   |   |   |   |   | security concerns |   |   |   |  
paypal | universal |   | International users | globally accepted,secure,can link to credit/debit cards (versatile) |   |   |   |   |   | transaction fees, not everyone in thailand has paypal |   |   |   |  


</body>
</html>
