### ISSUE TITLE
slide update วันที่6/12/23

### ISSUE THREAD

**Issue by PhobThePang** [PhobThePang/MPCforus#7]
Weekly Slide Update
1. Create a new slide and link here.
2. Slide continuity of content.
3. Short and Compact content.
4. Make it understandable.
**Treat slides like notes

**Comment by PhobThePang** [comment]
https://docs.google.com/presentation/d/1tWBEcOlrcUCxjd7qgtf0bet9EPkXTo873X6ggz_qiTE/edit?usp=sharing

**Comment by ICON08** [comment]
https://docs.google.com/presentation/d/1tWBEcOlrcUCxjd7qgtf0bet9EPkXTo873X6ggz_qiTE/edit?usp=sharing
